/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_camilotk_hellojni_HelloWorldJNI */

#ifndef _Included_br_com_camilotk_hellojni_HelloWorldJNI
#define _Included_br_com_camilotk_hellojni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_camilotk_hellojni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_camilotk_hellojni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
